server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ca7yqvnelwuw.ap-northeast-2.rds.amazonaws.com:3306/back-20220829
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

mybatis:
  mapper-locations:
    - /mappers/*.xml